name: Build 
jobs:
  make:
    name: Build Tweak
    runs-on: macos-latest
    env:
      THEOS: theos
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          submodules: true
      - name: Install ldid and xz
        run: |
          brew install ldid xz
      - name: Select Xcode
        run: sudo xcode-select --switch /Applications/Xcode_11.7.app 
      - name: Setup Theos
        uses: actions/checkout@master
        with:
          repository: theos/theos
          path: theos
          submodules: recursive
      - name: Download SDKs
        run: |
          curl -LO https://github.com/SamHep0803/iOS-13-Patched-SDK/archive/master.zip
          TMP=$(mktemp -d)
          unzip master.zip -d $TMP
          mv $TMP/iOS-13-Patched-SDK-master/*.sdk theos/sdks
          rm -r master.zip $TMP
      - name: Build Tweak
        run: |
         make clean package FINALPACKAGE=1
      - name: Upload To GitHub Artifacts
        uses: actions/upload-artifact@v2.2.2
        with:
          path: ./packages/*.deb
